### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by k94ll13nn3** [k94ll13nn3/Crabtopus#9]
Initial version:
- [x] Fix split cards mana cost (missing //)
- [x] Add missing mana symbols
- [x] Add GitHub actions CI
- [x] What will happen after new version of MTGA? 
  - **April 16th:** the model has changed! 😢 
- [x] Fix loading of cards when a new version is available (currently it deletes decks!)
- [x] Add about window with nuget packages used
- [x] See why AngleSharp 0.14 is not working.
- [x] Add UI for when decks are loading
- [x] Add button to load decks

Future features:
- [ ] Ability to see if a deck is already in the player's decks.
- [ ] Ability to see if a all cards from a deck are in the player's collection
- [ ] Show player ressources?
- [ ] Show missing cards summary (with wildcard sum) for a deck?
- [ ] Ability to chose land style
- [ ] Display version somewhere
- [ ] Set completion status?
- [ ] Filter tournaments by date, rating, number of decks ...
- [ ] See how companion is handled
- [ ] Search for deck with specific card
- [ ] // load of decks
